name: Update LOC by Language

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install GitHub CLI and cloc
      run: |
        sudo apt-get update
        sudo apt-get install -y cloc gh

    - name: Clone all your repos (private + public)
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        mkdir repos
        cd repos
        gh repo list simplysuvi --limit 100 --json nameWithOwner,visibility --jq '.[] | select(.visibility != "archived") | .nameWithOwner' |
        xargs -L1 gh repo clone


    - name: Count LOC per language
      run: |
        cd repos
        cloc . --out=cloc_report.txt
        tail -n +3 cloc_report.txt | head -n -2 | awk '{printf "| %s | %s |\n", $1, $5}' > ../lang_table.md

    - name: Update README with LOC stats
      run: |
        cd ..
        awk '/<!--START_LANG_STATS-->/ {print; system("cat lang_table.md"); next} /<!--END_LANG_STATS-->/ {print; next}1' README.md > README.tmp
        mv README.tmp README.md

    - name: Commit and Push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'actions@github.com'
        git add README.md
        git diff --cached --quiet || (git commit -m "Update LOC stats" && git push)
