name: Update LOC by Language

on:
  schedule:
    - cron: '0 2 * * 1'  # every Monday 2 AM
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install cloc
      run: sudo apt-get install -y cloc

    - name: Clone all your repos (private + public)
      run: |
        mkdir repos
        cd repos
        gh auth login --with-token < <(echo "${{ secrets.GH_PAT }}")
        gh repo list simplysuvi --limit 100 --json nameWithOwner,visibility --jq '.[] | select(.visibility != "archived") | .nameWithOwner' |
        xargs -L1 gh repo clone

    - name: Count LOC per language
      run: |
        cd repos
        cloc . --by-language --out=cloc_report.txt
        tail -n +2 cloc_report.txt | head -n -1 | awk '{printf "| %s | %s |\n", $1, $5}' > ../lang_table.md

    - name: Update README
      run: |
        cd ..
        awk '/<!--START_LANG_STATS-->/ {print; system("cat lang_table.md"); next} /<!--END_LANG_STATS-->/ {print; next}1' README.md > new.md
        mv new.md README.md

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update LOC stats"
        git push
